export type AppItem={slug:string;title:string;short:string;tagline:string;summary:string;badge:string;icon:string;logo:string;audience:string;highlights:readonly string[];availability:string;accent:string};
export const APPS:AppItem[]=[
{slug:"hocker-one",title:"Hocker ONE",short:"Control operativo",tagline:"Centro de control para procesos, métricas y aprobaciones.",summary:"Plataforma central para visualizar indicadores, procesos, aprobaciones y herramientas empresariales desde una sola experiencia.",badge:"Control",icon:"/apps/hocker-one/icon.png",logo:"/apps/hocker-one/logo-horizontal.png",audience:"Dirección, operación y equipos que necesitan visibilidad.",highlights:["Paneles","Aprobaciones","Indicadores"],availability:"Disponible para evaluación",accent:"#60a5fa"},
{slug:"hocker-ads",title:"Hocker Ads",short:"Marketing y adquisición",tagline:"Servicios y producto para convertir demanda en crecimiento medible.",summary:"Estrategia, creatividad, funnels, automatización y analítica conectados a objetivos comerciales.",badge:"Marketing",icon:"/apps/hocker-ads/icon.png",logo:"/apps/hocker-ads/logo-horizontal.png",audience:"Marcas y negocios que necesitan captar y convertir demanda.",highlights:["Campañas","Contenido","Funnels"],availability:"Implementación bajo alcance",accent:"#22d3ee"},
{slug:"hocker-hub",title:"Hocker Hub",short:"CRM y seguimiento",tagline:"Leads, clientes y oportunidades en una sola vista.",summary:"Centraliza contactos, conversaciones, tareas, pipeline y seguimiento comercial.",badge:"CRM",icon:"/apps/hocker-hub/icon.png",logo:"/apps/hocker-hub/logo-horizontal.png",audience:"Equipos comerciales, soporte y atención al cliente.",highlights:["Leads","Pipeline","Seguimiento"],availability:"Implementación bajo alcance",accent:"#38bdf8"},
{slug:"hocker-drive-cloud",title:"Hocker Drive Cloud",short:"Información y respaldo",tagline:"Archivos, evidencia y conocimiento con continuidad.",summary:"Organiza documentos, activos, evidencias y conocimiento empresarial.",badge:"Cloud",icon:"/apps/hocker-drive-cloud/icon.png",logo:"/apps/hocker-drive-cloud/logo-horizontal.png",audience:"Equipos que necesitan ordenar información y mantener continuidad.",highlights:["Respaldo","Búsqueda","Colaboración"],availability:"Implementación bajo alcance",accent:"#8b7cf6"},
{slug:"hocker-wallet",title:"Hocker Wallet",short:"Wallet y pagos",tagline:"Capa financiera conectable sujeta a integraciones y cumplimiento.",summary:"Concepto y desarrollo por etapas para administrar saldos, movimientos, cobros y subwallets especializadas.",badge:"Finanzas",icon:"/apps/hocker-wallet/icon.png",logo:"/apps/hocker-wallet/logo-horizontal.png",audience:"Casos que requieran una capa financiera conectable y cumplimiento aplicable.",highlights:["Saldos","Pagos","Subwallets"],availability:"Desarrollo por etapas",accent:"#fbbf24"},
{slug:"chido-casino",title:"Chido Casino",short:"Entretenimiento digital",tagline:"Gaming con comunicación responsable y alcance regulado.",summary:"Plataforma de entretenimiento digital sujeta a disponibilidad, jurisdicción y cumplimiento aplicable.",badge:"Gaming",icon:"/apps/chido-casino/icon.png",logo:"/apps/chido-casino/logo-horizontal.png",audience:"Personas adultas donde el servicio sea legal y esté disponible.",highlights:["Experiencia","Promociones","Responsabilidad"],availability:"Información bajo solicitud",accent:"#f97316"},
{slug:"trackhok",title:"Trackhok",short:"Monitoreo y logística",tagline:"Ubicación, rutas y alertas para operaciones autorizadas.",summary:"Diseño objetivo para seguimiento de activos, flotas, rutas y eventos con autorización.",badge:"Operación",icon:"/apps/trackhok/icon.png",logo:"/apps/trackhok/logo-horizontal.png",audience:"Logística, activos y flotas con uso autorizado.",highlights:["Rutas","Alertas","Telemetría"],availability:"Información bajo solicitud",accent:"#cbd5e1"},
{slug:"nexpa",title:"NEXPA",short:"Bienestar digital",tagline:"Seguridad y bienestar con consentimiento y límites claros.",summary:"Diseño objetivo de herramientas preventivas y de bienestar digital alrededor del consentimiento.",badge:"Seguridad",icon:"/apps/nexpa/icon.png",logo:"/apps/nexpa/logo-horizontal.png",audience:"Familias y organizaciones con casos legítimos y consentidos.",highlights:["Consentimiento","Prevención","Alertas"],availability:"Información bajo solicitud",accent:"#32d5e8"},
{slug:"hocker-up",title:"Hocker Up",short:"Aprendizaje y comunidad",tagline:"Aprendizaje, mentoría y comunidad conectados.",summary:"Diseño objetivo para cursos, mentorías, perfiles profesionales y colaboración.",badge:"Learning",icon:"/apps/hocker-up/icon.png",logo:"/apps/hocker-up/logo-horizontal.png",audience:"Creadores, alumnos, mentores y marcas educativas.",highlights:["Cursos","Mentoría","Comunidad"],availability:"Próximamente",accent:"#7c6cff"},
{slug:"hocker-supply",title:"Hocker Supply",short:"Manufactura y fulfillment",tagline:"De la idea al producto, producción e inventario.",summary:"Solución en consolidación para mercancía, proveedores, catálogo, pedidos y logística.",badge:"Supply",icon:"/apps/hocker-supply/icon.png",logo:"/apps/hocker-supply/logo-horizontal.png",audience:"Marcas y creadores que necesitan producir y distribuir mercancía.",highlights:["On demand","Merch","Supply chain"],availability:"Implementación bajo alcance",accent:"#ff8a1f"}
];
