export type EvidenceState="VERIFIED"|"DOCUMENTED"|"PRIVATE"|"IN_PROGRESS"|"ARCHIVED";
export type EvidenceCategory="ai"|"engineering"|"growth"|"creative"|"leadership";
export type EvidenceItem={id:string;projectId:string;category:EvidenceCategory;title:string;summary:string;role:string;date:string;media:readonly string[];proofType:"ui"|"code"|"campaign"|"video"|"diagram"|"credential"|"document";visibility:"PUBLIC"|"PRIVATE";source:string|null;metric:string|null;metricSource:string|null;status:EvidenceState;demonstrates:string};
export const EVIDENCE:EvidenceItem[]=[
{id:"hocker-web",projectId:"hocker-agi",category:"engineering",title:"Sitio, producto y releases HOCKER",summary:"Arquitectura web, QA, seguridad, documentación y releases verificables del ecosistema.",role:"Producto · Ingeniería · UX",date:"2026",media:[],proofType:"code",visibility:"PUBLIC",source:"GitHub / producción HOCKER",metric:null,metricSource:null,status:"VERIFIED",demonstrates:"Capacidad para convertir decisiones de producto en código, pruebas y releases."},
{id:"hocker-agis",projectId:"hocker-agi",category:"ai",title:"Modelo de AGIs gobernadas",summary:"Diseño funcional de agentes especializados, outputs estructurados, evidencia y Owner Gate.",role:"AI Systems Architecture",date:"2026",media:[],proofType:"diagram",visibility:"PUBLIC",source:"Documentación y repositorios HOCKER",metric:null,metricSource:null,status:"VERIFIED",demonstrates:"Diseño de sistemas IA con límites de ejecución y gobernanza."},
{id:"score-store",projectId:"score-store",category:"growth",title:"Score Store · ecommerce & performance",summary:"Diseño de experiencia ecommerce, catálogo, copy, estructura de conversión, pagos, envíos, tracking y sistema creativo, según el CV.",role:"Ecommerce · UX · Growth",date:"Proyecto destacado",media:[],proofType:"campaign",visibility:"PUBLIC",source:"CV actual; materiales visuales pendientes",metric:null,metricSource:null,status:"DOCUMENTED",demonstrates:"Conexión entre experiencia, tracking, creatividad y conversión."},
{id:"pinocho",projectId:"career",category:"creative",title:"Proyecto Pinocho · postproducción Stop Motion",summary:"Parte del equipo de postproducción que colaboró en el filme Pinocho; edición y montaje audiovisual en entorno de animación artesanal, según el CV proporcionado.",role:"Editor Audiovisual (Stop Motion)",date:"2021–2022",media:[],proofType:"credential",visibility:"PUBLIC",source:"CV actual; evidencia publicable pendiente",metric:null,metricSource:null,status:"DOCUMENTED",demonstrates:"Experiencia declarada de postproducción audiovisual en un proyecto stop motion de alto nivel."},
{id:"monsat-growth",projectId:"career",category:"growth",title:"Generación de leads y contenido",summary:"Campañas, segmentación y contenido para Monsat Monitoreo Satelital.",role:"Marketing Digital · Content Manager",date:"2023–2025",media:[],proofType:"campaign",visibility:"PRIVATE",source:"CV actual; capturas/métricas pendientes",metric:null,metricSource:null,status:"DOCUMENTED",demonstrates:"Aplicación de performance marketing y contenido a objetivos de adquisición."},
{id:"aries-multidisciplinary",projectId:"career",category:"leadership",title:"Marketing + desarrollo",summary:"Gestión integral de redes, campañas, branding local, comunidad y soporte de desarrollo en Grupo Aries.",role:"Social Media Manager · Developer",date:"2025",media:[],proofType:"document",visibility:"PRIVATE",source:"CV actual; entregables pendientes",metric:null,metricSource:null,status:"DOCUMENTED",demonstrates:"Capacidad para conectar ejecución creativa, marketing y tecnología."}
];
