import test from"node:test";import assert from"node:assert/strict";import{readFileSync,existsSync}from"node:fs";const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
test("professional portfolio is recruiter-facing evidence route",()=>{assert.equal(existsSync(new URL("../src/app/portafolio/page.tsx",import.meta.url)),true);const p=read("src/app/portafolio/page.tsx");assert.match(p,/ProfilePage|buildProfileSchema/);assert.match(p,/EvidenceWall/);assert.match(p,/No me creas\. Revísalo\./)});
test("legacy portfolio redirects and cases exist",()=>{assert.match(read("src/app/portfolio/page.tsx"),/permanentRedirect\("\/portafolio"\)/);assert.equal(existsSync(new URL("../src/app/casos/page.tsx",import.meta.url)),true)});
test("public structured data does not invent legal entity",()=>{assert.doesNotMatch(read("src/lib/public-site.ts"),/legalName\s*:/);assert.doesNotMatch(read("src/lib/seo/schema.ts"),/legalName\s*:/);assert.doesNotMatch(read("src/app/layout.tsx"),/keywords\s*:/);assert.doesNotMatch(read("src/app/empresa/page.tsx"),/empresa mexicana/i)});
test("legal pages distinguish brand from legal identity",()=>{assert.match(read("src/app/legal/privacy/page.tsx"),/marca del proyecto/i);assert.match(read("src/app/legal/terms/page.tsx"),/no acredita por sí mismo una entidad jurídica/i)});
test("sitemap avoids synthetic freshness",()=>{const s=read("src/app/sitemap.ts");assert.doesNotMatch(s,/new Date\(/);assert.doesNotMatch(s,/priority\s*:/);assert.doesNotMatch(s,/changeFrequency\s*:/);assert.match(s,/PORTFOLIO_CASES/)});
test("Home uses approved TRIAD funnel",()=>{const h=read("src/app/page.tsx")+read("src/components/editorial/home-hero.tsx");assert.match(h,/Ideas que funcionan\. Sistemas que evolucionan\./);assert.match(h,/¿Qué quieres crear\?/);assert.doesNotMatch(h,/∞|SYSTEM VIEW|CONTROL PLANE|GOVERNED/)});
test("AGI page keeps internal architecture off the public surface",()=>{const a=read("src/app/agis/page.tsx")+read("src/components/agi/mission-selector.tsx")+read("src/content/agi/public-missions.ts");assert.doesNotMatch(a,/Owner Gate|VISUAL_ONLY|memoria privada|runtime productivo|repositorios/i);assert.doesNotMatch(a,/VERTX|REVIA|JURIX|SYNTIA|HOSTIA/);assert.match(a,/DEMO INTERACTIVA|experiencia interactiva/i)});
test("public contact uses icon actions and lead handoff avoids popup coupling",()=>{const p=read("src/app/page.tsx")+read("src/app/contacto/page.tsx")+read("src/components/navigation/site-footer.tsx")+read("src/components/ui/contact-actions.tsx");assert.match(p,/contact-icon-actions/);assert.match(p,/wa\.me/);assert.match(p,/tel:/);assert.match(p,/mailto:/);const f=read("src/components/lead-form.tsx");assert.doesNotMatch(f,/window\.open\(/);assert.match(f,/Continuar por WhatsApp/)});

test("public security posture is explicit",()=>{const n=read("next.config.ts");assert.match(n,/Strict-Transport-Security/);assert.match(n,/Content-Security-Policy/);assert.match(n,/X-Content-Type-Options/);assert.match(n,/X-Frame-Options/);assert.match(n,/X-Permitted-Cross-Domain-Policies/);const s=read("public/.well-known/security.txt");assert.match(s,/Contact: mailto:/);assert.match(s,/Policy: https:/)});
