import test from"node:test";import assert from"node:assert/strict";import{readFileSync,existsSync}from"node:fs";const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
test("professional portfolio is recruiter-facing evidence route",()=>{assert.equal(existsSync(new URL("../src/app/portafolio/page.tsx",import.meta.url)),true);const p=read("src/app/portafolio/page.tsx");assert.match(p,/ProfilePage|buildProfileSchema/);assert.match(p,/EvidenceWall/);assert.match(p,/No me creas\. Revísalo\./)});
test("legacy portfolio redirects and cases exist",()=>{assert.match(read("src/app/portfolio/page.tsx"),/permanentRedirect\("\/portafolio"\)/);assert.equal(existsSync(new URL("../src/app/casos/page.tsx",import.meta.url)),true)});
test("public structured data does not invent legal entity",()=>{assert.doesNotMatch(read("src/lib/public-site.ts"),/legalName\s*:/);assert.doesNotMatch(read("src/lib/seo/schema.ts"),/legalName\s*:/);assert.doesNotMatch(read("src/app/layout.tsx"),/keywords\s*:/);assert.doesNotMatch(read("src/app/empresa/page.tsx"),/empresa mexicana/i)});
test("legal pages distinguish brand from legal identity",()=>{assert.match(read("src/app/legal/privacy/page.tsx"),/marca del proyecto/i);assert.match(read("src/app/legal/terms/page.tsx"),/no acredita por sí mismo una entidad jurídica/i)});
test("sitemap avoids synthetic freshness",()=>{const s=read("src/app/sitemap.ts");assert.doesNotMatch(s,/new Date\(/);assert.doesNotMatch(s,/priority\s*:/);assert.doesNotMatch(s,/changeFrequency\s*:/);assert.match(s,/PORTFOLIO_CASES/)});
test("Home uses approved TRIAD funnel",()=>{const h=read("src/app/page.tsx")+read("src/components/editorial/home-hero.tsx");assert.match(h,/Ideas que funcionan\. Sistemas que evolucionan\./);assert.match(h,/¿Qué quieres crear\?/);assert.doesNotMatch(h,/∞|SYSTEM VIEW|CONTROL PLANE|GOVERNED/)});
test("AGI page is governed visual only",()=>{const a=read("src/app/agis/page.tsx")+read("src/components/agi/mission-selector.tsx")+read("src/content/agi/public-missions.ts");assert.match(a,/Owner Gate/);assert.match(a,/acciones materiales/i);assert.match(a,/VISUAL_ONLY|no invoca|no ejecuta/i);assert.doesNotMatch(a,/autonom[ií]a total|completamente aut[oó]nom/i)});
test("privacy is revocable and leads remain bounded",()=>{const c=read("src/components/analytics-consent.tsx");assert.match(c,/hocker\.consent\.v2/);assert.match(c,/Cambiar preferencias/);const r=read("src/app/api/leads/route.ts");assert.match(r,/content-length/i);assert.match(r,/origin/i);assert.match(r,/content-type/i)});
