import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { APPS } from "@/lib/site-data";
import { publicReadiness } from "@/lib/product-readiness";

type PageProps = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { slug } = await params; const app = APPS.find((item) => item.slug === slug); if (!app) return { title: "Producto" }; return { title: app.title, description: app.summary, alternates: { canonical: `/apps/${app.slug}` }, openGraph: { title: app.title, description: app.summary, images: [{ url: app.ogImage, width: 1200, height: 630, alt: app.title }] }, twitter: { card: "summary_large_image", title: app.title, description: app.summary, images: [app.ogImage] } }; }
export default async function AppDetailPage({ params }: PageProps) {
  const { slug } = await params; const app = APPS.find((item) => item.slug === slug); if (!app) return notFound(); const readiness = publicReadiness(app.slug, app.availability);
  return <><section className="page-hero commercial-page-hero product-detail-hero"><div className="container detail-layout product-detail-layout"><div><p className="eyebrow">{app.badge}</p><h1 className="hero-title">{app.title}</h1><p className="hero-text">{app.summary}</p><div className="product-public-tags"><span>{app.audience}</span><span>{readiness}</span></div><div className="hero-actions"><Link href="/contacto" className="button button-primary button-big">Solicitar evaluación</Link><Link href="/apps" className="button button-secondary button-big">Ver productos</Link></div></div><div className="product-cover-wrap"><Image src={app.cover} alt={`Identidad y propuesta de ${app.title}`} width={1600} height={900} sizes="(max-width: 900px) 100vw, 52vw" className="hero-cover product-detail-cover" priority /></div></div></section><section className="section"><div className="container"><div className="section-head split-head"><div><p className="eyebrow">PROPÓSITO</p><h2>{app.tagline}</h2></div><p>{app.summary}</p></div><div className="product-benefit-grid">{app.highlights.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>Esta capacidad se configura según el proceso, permisos, integraciones y criterios de aceptación definidos para el proyecto.</p></article>)}</div></div></section><section className="section section-contrast"><div className="container product-fit-grid"><div><p className="eyebrow">DISEÑADO PARA</p><h2>{app.audience}</h2></div><div><h3>Madurez pública</h3><p>{readiness}. La disponibilidad real se confirma según evidencia, integración, seguridad y regulación aplicable.</p><h3>Implementación modular</h3><p>El producto evoluciona por etapas y se conecta con otras capas únicamente cuando existe una necesidad validada y un contrato técnico claro.</p></div></div></section><section className="section"><div className="container proposal-panel"><div><p className="eyebrow">SIGUIENTE PASO</p><h2>Confirma si este producto encaja con tu operación.</h2><p>Revisamos el proceso, resultado esperado, integraciones y nivel de personalización antes de cotizar o activar capacidades.</p></div><Link href="/contacto" className="button button-primary button-big">Solicitar diagnóstico</Link></div></section></>;
}
